apiVersion: v1
kind: Namespace
metadata:
  name: test-echo


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
spec:
  rules:
    - host: echo.v1.127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echoserver
                port:
                  number: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
      tier: app
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echoserver
          image: truelsy/echoserver:latest

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
      app: echo
      tier: app
